const http = require('node:http');
const fs = require('node:fs/promises');
const path = require('node:path');
const crypto = require('node:crypto');

const PORT = Number(process.env.PORT || 4173);
const DATA = path.join(__dirname, 'data.json');
const seed = { users: [], services: [
  { id:'svc-cut',name:'Haircut',price:100,duration:60,active:true },
  { id:'svc-beard',name:'Beard Trim',price:80,duration:60,active:true },
  { id:'svc-combo',name:'Hair & Beard',price:150,duration:90,active:true },
  { id:'svc-style',name:'Hair Styling',price:80,duration:60,active:true },
  { id:'svc-color',name:'Hair Color',price:200,duration:60,active:true }
], barbers:[{id:'barber-1',name:'Ahmed Mansour',specialty:'Master Barber',hours:{start:'10:00',end:'22:00'},daysOff:[],blocked:[]}], bookings:[], sessions:[] };
async function readDb(){try{const db=JSON.parse(await fs.readFile(DATA,'utf8'));for(const s of db.services){s.duration=s.duration||(s.id==='svc-combo'?90:60);s.name=({ 'svc-cut':'Haircut','svc-beard':'Beard Trim','svc-combo':'Hair & Beard','svc-style':'Hair Styling','svc-color':'Hair Color' })[s.id]||s.name}if(db.barbers[0]?.id==='barber-1'){db.barbers[0].name='Ahmed Mansour';db.barbers[0].specialty='Master Barber'}return db}catch{return structuredClone(seed)}}
async function locked(fn){const lock=DATA+'.lock'; let acquired=false; for(let i=0;i<300;i++){try{await fs.mkdir(lock);acquired=true;break}catch(e){if(e.code!=='EEXIST')throw e;await new Promise(r=>setTimeout(r,15))}} if(!acquired)throw Object.assign(new Error('Could not complete the request. Please try again.'),{status:503}); try{const db=await readDb();const result=await fn(db);const tmp=DATA+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(tmp,JSON.stringify(db,null,2));await fs.rename(tmp,DATA);return result}finally{await fs.rm(lock,{recursive:true,force:true})}}
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'no-store'});res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const chunk of req)s+=chunk;if(s.length>1e6)throw Object.assign(new Error('Request is too large.'),{status:413});return s?JSON.parse(s):{}}
function token(){return crypto.randomBytes(32).toString('hex')}
function auth(req,db,role){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const session=db.sessions.find(x=>x.token===t);const user=session&&db.users.find(x=>x.id===session.userId);if(!user)throw Object.assign(new Error('Sign in to continue.'),{status:401});if(role&&user.role!==role)throw Object.assign(new Error('This page is for barbers.'),{status:403});return user}
function dateValid(s){return /^\d{4}-\d\d-\d\d$/.test(s)&&s>=new Date().toISOString().slice(0,10)}
function available(db,barberId,date,duration=60,ignoreId=null){const b=db.barbers.find(x=>x.id===barberId);if(!b||!dateValid(date)||b.daysOff.includes(new Date(date+'T12:00:00').getDay()))return[];const out=[];const [sh,sm]=b.hours.start.split(':').map(Number),[eh,em]=b.hours.end.split(':').map(Number),now=new Date(),today=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0'),current=now.getHours()*60+now.getMinutes(),end=eh*60+em;for(let m=sh*60+sm;m+duration<=end;m+=30){const time=String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');const key=date+'T'+time;const booked=db.bookings.some(x=>{if(x.id===ignoreId||x.barberId!==barberId||x.status!=='confirmed'||x.start.slice(0,10)!==date)return false;const [h,mi]=x.start.slice(11).split(':').map(Number),bs=h*60+mi;return m<bs+(x.duration||60)&&m+duration>bs});const blocked=b.blocked.some(k=>{if(!k.startsWith(date+'T'))return false;const [h,mi]=k.slice(11).split(':').map(Number),bs=h*60+mi;return m<bs+60&&m+duration>bs});const busy=booked||blocked||(date===today&&m<=current);out.push({time,available:!busy})}return out}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS'});return res.end()}
try{const url=new URL(req.url,'http://localhost');const p=url.pathname;let result;
if(p.startsWith('/api/')){
if(p==='/api/auth/signup'&&req.method==='POST'){const x=await body(req);if(!x.name||!x.email||!x.password||x.password.length<6)throw Object.assign(new Error('Enter your name, email, and a password with at least 6 characters.'),{status:400});result=await locked(db=>{if(db.users.some(u=>u.email===x.email.toLowerCase()))throw Object.assign(new Error('This email is already registered.'),{status:409});const user={id:crypto.randomUUID(),name:x.name.trim(),email:x.email.toLowerCase(),role:x.role==='barber'?'barber':'customer',salt:crypto.randomBytes(16).toString('hex')};user.hash=crypto.scryptSync(x.password,user.salt,64).toString('hex');db.users.push(user);const t=token();db.sessions.push({token:t,userId:user.id});return{token:t,user:{id:user.id,name:user.name,email:user.email,role:user.role}}})}
else if(p==='/api/auth/login'&&req.method==='POST'){const x=await body(req);result=await locked(db=>{const u=db.users.find(v=>v.email===String(x.email||'').toLowerCase());if(!u||crypto.scryptSync(String(x.password||''),u.salt,64).toString('hex')!==u.hash)throw Object.assign(new Error('Email or password is incorrect.'),{status:401});const t=token();db.sessions.push({token:t,userId:u.id});return{token:t,user:{id:u.id,name:u.name,email:u.email,role:u.role}}})}
else if(p==='/api/auth/me'&&req.method==='GET'){const db=await readDb();const u=auth(req,db);result={user:{id:u.id,name:u.name,email:u.email,role:u.role}}}
else if(p==='/api/services'&&req.method==='GET'){const db=await readDb();result={services:db.services.filter(s=>s.active)}}
else if(p==='/api/barber/services'&&req.method==='GET'){const db=await readDb();auth(req,db,'barber');result={services:db.services}}
else if(p==='/api/barbers'&&req.method==='GET'){const db=await readDb();result={barbers:db.barbers}}
else if(p==='/api/availability'&&req.method==='GET'){const db=await readDb();const service=db.services.find(s=>s.id===url.searchParams.get('serviceId')&&s.active);result={slots:available(db,url.searchParams.get('barberId'),url.searchParams.get('date'),service?.duration||60)}}
else if(p==='/api/bookings'&&req.method==='GET'){const db=await readDb();const u=auth(req,db);result={bookings:db.bookings.filter(b=>u.role==='barber'?b.barberId===db.barbers[0].id:b.customerId===u.id).sort((a,b)=>a.start.localeCompare(b.start))}}
else if(p==='/api/bookings'&&req.method==='POST'){const x=await body(req);result=await locked(db=>{const u=auth(req,db,'customer');const service=db.services.find(s=>s.id===x.serviceId&&s.active),barber=db.barbers.find(b=>b.id===x.barberId);if(!service||!barber||!dateValid(x.date)||!/^\d\d:\d\d$/.test(x.time))throw Object.assign(new Error('Booking details are incomplete.'),{status:400});if(!available(db,barber.id,x.date,service.duration).some(s=>s.time===x.time&&s.available))throw Object.assign(new Error('Sorry, that time was just booked. Please choose another.'),{status:409});const item={id:crypto.randomUUID(),customerId:u.id,customerName:u.name,serviceId:service.id,serviceName:service.name,price:service.price,barberId:barber.id,barberName:barber.name,start:x.date+'T'+x.time,duration:service.duration,status:'confirmed',createdAt:new Date().toISOString()};db.bookings.push(item);return{booking:item}})}
else if(p.startsWith('/api/bookings/')&&req.method==='PATCH'){const id=p.split('/').pop(),x=await body(req);result=await locked(db=>{const u=auth(req,db),b=db.bookings.find(v=>v.id===id&&v.status==='confirmed'&&(u.role==='barber'||v.customerId===u.id));if(!b)throw Object.assign(new Error('Booking not found.'),{status:404});if(x.action==='cancel'){b.status='cancelled';return{booking:b}}if(x.action==='reschedule'){if(!dateValid(x.date)||!available(db,b.barberId,x.date,b.duration||60,id).some(s=>s.time===x.time&&s.available))throw Object.assign(new Error('That time is unavailable.'),{status:409});b.start=x.date+'T'+x.time;return{booking:b}}throw Object.assign(new Error('Unknown request.'),{status:400})})}
else if(p==='/api/barber/settings'&&req.method==='PATCH'){const x=await body(req);result=await locked(db=>{const u=auth(req,db,'barber'),b=db.barbers.find(v=>v.id===db.barbers[0].id);if(x.start&&x.end){if(x.start>=x.end)throw Object.assign(new Error('Closing time must be later than opening time.'),{status:400});b.hours={start:x.start,end:x.end}}if(x.block){const key=x.block.date+'T'+x.block.time;if(!dateValid(x.block.date)||!/^\d\d:\d\d$/.test(x.block.time))throw Object.assign(new Error('Invalid time details.'),{status:400});if(!b.blocked.includes(key))b.blocked.push(key)}if(x.unblock)b.blocked=b.blocked.filter(k=>k!==x.unblock);if(x.serviceId){const s=db.services.find(s=>s.id===x.serviceId);if(s){if(x.name)s.name=x.name;if(Number.isFinite(x.price))s.price=x.price;if(typeof x.active==='boolean')s.active=x.active}}return{barber:{...b},services:db.services}})}
else throw Object.assign(new Error('Route not found.'),{status:404});json(res,200,result);return}
const file=p==='/'?path.join(__dirname,'index.html'):path.join(__dirname,p.slice(1));if(!file.startsWith(__dirname))return json(res,403,{error:'Forbidden.'});try{const data=await fs.readFile(file);const type=file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript; charset=utf-8':file.endsWith('.webmanifest')?'application/manifest+json':file.endsWith('.png')?'image/png':'application/octet-stream';res.writeHead(200,{'content-type':type});res.end(data)}catch{json(res,404,{error:'Page not found.'})}
}catch(e){json(res,e.status||500,{error:e.message||'An unexpected error occurred.'})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`Barber Booking ready at http://localhost:${PORT}`));

